EXPLAIN SELECT * FROM BOOKS WHERE TITLE= "Man's Fate";
CREATE INDEX IDX_BOOKS_TITLE ON BOOKS(TITLE);
EXPLAIN SELECT * FROM BOOKS WHERE TITLE= "Man's Fate";

EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME="John";
CREATE INDEX IDX_READERS_FLNAMES ON READERS(FIRSTNAME, LASTNAME);
EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME="John";


